apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: 3scale-monitor
  namespace: 3scale
spec:
  serviceAccountName: prometheus-k8s
  podMonitorSelector:
   matchExpressions:
   - key: app
     operator: In
     values:
     - 3scale-api-management
  ruleSelector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - 3scale-api-management
