---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-api
  namespace: status-api
  labels:
    app: status-api
    app.kubernetes.io/component: status-api
    app.kubernetes.io/instance: status-api
spec:
  selector:
    matchLabels:
      deployment: status-api
  replicas: 1
  template:
    metadata:
      labels:
        deployment: status-api
    spec:
      containers:
        - name: status-api
          image: quay.io/ealvarez/status-api:5
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: status-api
  namespace: status-api
spec:
  selector:
    deployment: status-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: status-api
  namespace: status-api
spec:
  host: status-api.apps.ocp4.example.com
  to:
    kind: Service
    name: status-api
  port:
    targetPort: 8080
  tls:
    termination: edge
