---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petshelter-api
spec:
  selector:
    matchLabels:
      app: petshelter-api
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: petshelter-api
        version: v1
    spec:
      containers:
        - name: petshelter-api
          image: quay.io/redhattraining/3scale-petshelter:1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: petshelter-api
spec:
  selector:
    app: petshelter-api
    version: v1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080